name: CI

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rustup Targets
        run: |
          rustup target add aarch64-apple-ios-sim
          rustup target add aarch64-apple-ios
          rustup target add x86_64-apple-ios
      - name: Install Swift Bridge CLI
        run: cargo install swift-bridge-cli
      - name: Build Rust binaries
        run: ./build-rust.sh
      - name: Build Swift package
        run: |
          cd FluvioClientSwift
          xcodebuild -scheme FluvioClientSwift -destination 'platform=iOS Simulator,OS=15.4,name=iPhone SE (3rd generation)'
