name: CI

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rustup Targets
        run: |
          rustup target add aarch64-apple-ios-sim
          rustup target add aarch64-apple-ios
          rustup target add x86_64-apple-ios
      # - uses: Swatinem/rust-cache@v1
      #   with:
      #     cache-on-failure: true
      - name: Install Swift Bridge CLI
        run: cargo install swift-bridge-cli -f --version 0.1.32
      - name: Build Rust binaries
        run: ./build-rust.sh && du FluvioClientSwift
      - name: Build Swift package
        run: |
          cd FluvioClientSwift
          xcodebuild -scheme FluvioClientSwift -destination generic/platform=iOS
      - name: Run Swift Example tests
        run: |
          cd FluvioClientSwiftExample/
          xcodebuild test -scheme 'FluvioClientSwiftExample (iOS)' -project FluvioClientSwiftExample.xcodeproj  -destination 'platform=iOS Simulator,name=iPhone 12'
